### ISSUE TITLE
Documentation missing important details

### ISSUE THREAD

**Issue by gunnaraas** [crowdsecurity/home-assistant-addons#11]
The bouncer add-on [DOCS.md](https://github.com/crowdsecurity/home-assistant-addons/blob/main/crowdsec-firewall-bouncer/DOCS.md) would greatly benefit from a few content changes. 

It's not clearly documented that the user must input the API url and key information to `local_api_credentials.yaml` for this to work correctly.

Instructions about how to edit the config file would likely be useful considering the user base this tool is being promoted to, as files in `.storage` are inaccessible from the standard HA file editor and Cloudsec Terminal doesn't come with nano or vim preinstalled. If I'm not missing something, most users will need to install the Terminal & SSH add-on to edit these config files. 

The documentation also neglects to mention steps telling users how to enable the online API. While having that might extend beyond the scope of this add-on, if these docs are being shared in community forums as *the* official resource about how to use Crowdsec in HA, editing this into something more closely resembling a start-to-finish "Getting Started" guide would be recommended.

**Comment by gunnaraas** [comment]
The critical documentation issue about where the user needs to supply API information is fixed in #12. 
Ideally the program should edit these config files automatically without the need for user intervention, but this works as a temporary solution in the meantime.

**Comment by gunnaraas** [comment]
Thanks @he2ss, that is helpful and something I overlooked. The way these docs were written, I assumed I needed to update the YAML directly to get this working. I can update my PR to reflect this new knowledge, as doing it inside the UI is going to be significantly easier for most users..

**Comment by he2ss** [comment]
Yep, I can will be helpful. Thanks @gunnaraas !

**Comment by he2ss** [comment]
This issue can be closed thanks to @gunnaraas.
