### ISSUE TITLE
Notification Plugin Support

### ISSUE THREAD

**Issue by akeslo** [crowdsecurity/home-assistant-addons#24]
It appears that when the add-on starts it overwrites any changes made to /etc/crowdsec/profiles.yaml and /etc/crowdsec/notifications/email.yaml.  After making changes to these files via terminal, a restart of the add-on renders them back to the default.

**Comment by scaarup** [comment]
As the readme describes:
"This add-on has also persistent config and data files that are store at /config/.storage/crowdsec/."
