### ISSUE TITLE
HA Addon instructions fail at adding the repository

### ISSUE THREAD

**Issue by cjramseyer** [crowdsecurity/home-assistant-addons#44]
Following the instructions, they fail at the steps to add the specified repo via the URL in Home Assistant

![image](https://github.com/crowdsecurity/home-assistant-addons/assets/48690692/afa0fc11-0e77-4e60-908c-f9b4b00403a1)

**Comment by he2ss** [comment]
Hi,

There is no issue with the repository. I tried again now and seems to work.
Maybe it happened while github has an issue ? Can you try again please.

**Comment by cjramseyer** [comment]
Just retested, and now adding the repo is working successfully.  Thank you
