### ISSUE TITLE
crowdsec 1.6.0 high cpu

### ISSUE THREAD

**Issue by alpy-nz** [crowdsecurity/home-assistant-addons#49]
following upgrade to 1.6.0 from 1.5.4 crowdsec addon consumes much higher cpu - constant 60%... restoring 1.5.4 returns to normal 0%.

**Comment by alpy-nz** [comment]
host is proxmox      

 Core 2024.1.6
Supervisor 2024.01.1
Operating System 11.4

**Comment by he2ss** [comment]
Hi @alpy-nz,

We add new version. Can you test with the latest version please ?

**Comment by alpy-nz** [comment]
hi there thanks for the reply - tried the newer version and cpu again jumped up  on start to 59% and stayed at that level unfortunately

**Comment by he2ss** [comment]
Hi @alpy-nz,

Could you please come to [discord](https://discord.com/invite/crowdsec). Maybe it's better to troubleshoot together easily.
We will past the solution here to close the issue if we fix it.

**Comment by LaurenceJJones** [comment]
Since I wasn't apart of conversion, I will class issue as completed.

If this is not the case please reopen.
