### ISSUE TITLE
1.6.1 released

### ISSUE THREAD

**Issue by modem7** [crowdsecurity/home-assistant-addons#52]
Hey guys, 

1.6.1 has been released, not quite sure what needs updating to make this a reality. 

```console
WARN[2024-04-30T18:30:29+01:00] A new CrowdSec release is available (v1.6.1). Your version is 'v1.6.0'. Please update it to use new parsers/scenarios/collections.
```

@he2ss was able to do the last one, but I don't want to assume they'll be able to upgrade to next. 

Edit: Made a PR, unsure if it contains what's required.

Made a change to make it easier to change versions going forwards.

Cheers

**Comment by LaurenceJJones** [comment]
Apologizes, we now have `1.6.2` I will see about the update on monday
